name: EdgeX Snap Tester
description: |
  Github action for smoke testing of EdgeX snaps

inputs:
  name:
    description: Name of the testing suite
    required: true

runs:
  using: composite
  steps:
    - name: Install Snapcraft
      shell: bash
      run: |
        sudo snap install snapcraft --classic
    
    - name: Setup LXD
      shell: bash
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable

    - name: Run tests
      shell: bash
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: lxd
      run: |
        echo Running tests for: ${{ inputs.name }}
        cd ${{github.action_path}}
        go test -v ${{github.action_path}}/tests/${{inputs.name}}
