name: EdgeX Snap Tester
description: |
  Github action for smoke testing of EdgeX snaps

inputs:
  name:
    description: Name of the testing suite
    required: true
  snap:
    description: The name of the snap to be tested or the relative path to local snap
    required: true

runs:
  using: composite
  steps:
  
    - name: Run tests
      shell: bash
      # Set working directory to this repo, where tests are
      working-directory: ${{ github.action_path }}
      env:
        SNAP: ${{github.workspace}}/${{inputs.snap}}
      run: |
        go test -v ${{github.action_path}}/tests/${{inputs.name}}
