name: EdgeX Snap Tester
description: |
  Github action to test packaging of EdgeX snaps on source PRs

inputs:
  name:
    description: Name of the testing suite
    required: true

runs:
  using: composite
  steps:
    - name: Build the snap
      shell: bash
      run: |
        echo "TODO"

    - name: Run tests
      shell: bash
      run: |
        echo Running tests for: ${{ inputs.name }}
        cd ${{github.action_path}}
        go test -v ${{github.action_path}}/tests/${{inputs.name}}
    