name: Test Snaps

on:
  pull_request:
    branches: [ main ]
  # allow manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: 
          - device-mqtt
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build snap
        id: build
        uses: snapcore/action-build@v1
        
      - name: Run snap tests
        uses: canonical/edgex-snap-tests@action-test-runner-2
        with:
          name: ${{ matrix.name }}
          snap: ${{ steps.build.outputs.snap }}